<?php 

/**
 * Rocket Web Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is available through the world-wide-web at this URL:
 * http://www.rocketweb.com/RW-LICENSE.txt
 *
 * @category   RocketWeb
 * @package    RocketWeb_MageTesting
 * @copyright  Copyright (c) 2013 RocketWeb (http://www.rocketweb.com)
 * @author     Rocket Web Inc.
 * @license    http://www.rocketweb.com/RW-LICENSE.txt
 */

?>
<div id="wizard_step_dbbackup" class="wizard_block_hidden" title="<?php echo Mage::helper('magetesting')->__('Prepare your database backup'); ?>" style="display:none;">
    <div>
        <div class="step_container_description">
            <?php echo Mage::helper('magetesting')->__('Prepare your database backup in order to import store to Mage Testing.'); ?>
            <div style="padding-top:5px;" class="step_container_buttons">
                <strong><?php echo Mage::helper('magetesting')->__('Choose your database backup'); ?>:</strong> <br/>
                <select name="dbbackup" id="magetesting_dbbackup" style="width:400px;">
                <?php foreach ($this->getDbBackups() as $backup): ?>
                    <option value="<?php echo $backup; ?>"><?php echo $backup ?></option>
                <?php endforeach; ?>
                </select>
                <?php echo $this->getChildHtml('generate_dbbackup_button'); ?>
            </div>
        </div>
        <div class="step_container_completed">
            <span class="step_completed" style="display:none;"><?php echo Mage::helper('magetesting')->__('Completed'); ?></span>
        </div>
        <div class="step_container_incomplete">
            <span class="step_incomplete" style="display:none;"><?php echo Mage::helper('magetesting')->__('Incomplete'); ?></span>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div class="step_container_buttons">
        <span class="step_process" style="display:none;"><?php echo $this->getChildHtml('process_dbbackup_button'); ?></span>
    </div>
</div>

<script type="text/javascript">

    WizardObj.addStep('dbbackup', 'wizard_step_dbbackup');

</script>